version: '3.8'

services:
  # 1. The "Cloud" Provider (AWS Emulator)
  localstack:
    container_name: cognistream_cloud
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  # 2. The AI Worker (Your Python Logic)
  ai-processor:
    container_name: cognistream_ai
    build: ./ai-service
    environment:
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack

  # 3. The "Attractive UI" Server
  frontend:
    container_name: cognistream_ui
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html